// <auto-generated />
namespace PIS_Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedConnectionOrderToOrderStatusCh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedConnectionOrderToOrderStatusCh));
        
        string IMigrationMetadata.Id
        {
            get { return "202005072335437_AddedConnectionOrderToOrderStatusCh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
